### ISSUE TITLE
Fail to run mainnet spy

### ISSUE THREAD

**Issue by yanhaosh** [wormhole-foundation/relayer-engine#48]
When running `npm run mainnet-spy`,  it shows 

```
2023-01-26T01:25:15.757Z        WARN    dht/RtRefreshManager    rtrefresh/rt_refresh_manager.go:136     failed when refreshing routing table2 errors occurred:
        * failed to query for self, err=failed to find any peer in table
        * failed to refresh cpl=0, err=failed to find any peer in table
```

Another issue, will docker's port listen to all vaas in the wormhole's guardian main/ test network? I decode the vaa from the testnet, the emitter only comes from ChainId = 1.  How could I listen to all vaas in this network?

Thanks.

**Comment by JoeHowarth** [comment]
Hi @yanhaosh, thanks for finding that issue with the `npm run mainnet-spy` command!

As for getting vaas from other chains, this is configured on a plugin level. I'm guessing you ran the example project and only saw vaas from solana (chainId 1)? If so that's configured here: https://github.com/wormhole-foundation/relayer-engine/blob/main/example-project/plugins/dummy_plugin/config/devnet.json#L6

To listen to other emitters, add them to this list. Currently there is no way to listen to all vaas from all networks, but I also don't see a use-case. If you have one please let me know

**Comment by JoeHowarth** [comment]
Pr auto-closed this... : (

**Comment by JoeHowarth** [comment]
Ahh, so that's actually not a vaa generator, it's a live network running across all the different blockchain testnets wormhole is connected to. Where are you parsing the vaa? Is it inside the relayer engine or are you copying the data from stdout on the spy process (the one in docker)? If it's in the relayer engine these vaa have already been filtered down ([code](https://github.com/wormhole-foundation/relayer-engine/blob/main/relayer-engine/src/listener/spyEventSource.ts#L70-L90))

If you're still having issues, can you reach out to me on telegram @JoeHowarth or open another issue?
