### ISSUE TITLE
Alerting for low balance in wallets

### ISSUE THREAD

**Issue by gabzim** [wormhole-foundation/relayer-engine#61]
If a wallet runs out of funds, we should trigger a notification that goes beyond merely logging the error since it requires urgent attention.

We don't necessarily need to fire a hook directly from the relayer, we could emit metrics for the balances of each of the wallets and then using a monitoring system to configure rules for the balances there.

**Comment by solanoepalacio** [comment]
Hey guys @JoeHowarth @gabzim @SEJeff 
With @CiottiGiorgio, we [opened a PR](https://github.com/wormhole-foundation/relayer-engine/pull/82) for this funcionality.
We are still testing it, but I think it might be a good moment to do a quick review if possible :pray:

**Comment by CiottiGiorgio** [comment]
Expanding on this, we were thinking about the implicit dependency between chain configs from common config file and `pullBalances` function and testing.

Since the only relevant info is the wormhole chain id, we thought it could be a good idea to just pass a `ChainId[]` instead of `ChainConfigInfo[]`.
This way, we could easily decouple the wallet monitor component from the structure of the chain info and unit testing is also easier as we could just feed the date that is strictly needed.

**Comment by CiottiGiorgio** [comment]
Closed for the same reason that the associated  PR was closed.
